#!/usr/bin/env node
/**
 * Convert a Zarparia D1 backup (backup.json.gz, produced by src/index.ts)
 * into a plain .sql file consumable by `wrangler d1 execute --file`.
 *
 * Usage:
 *   node restore.mjs <backup.json.gz | backup.json> [--out restore.sql] [--batch 200]
 *
 * The generated file is schema first (CREATE TABLE / CREATE INDEX, in the
 * original migration order — already foreign-key-safe), then INSERT
 * statements per table in that same order, batched to keep individual
 * statements a sane size.
 *
 * See README.md for the full restore recipe (target-DB choice, dry run,
 * applying with wrangler).
 */

import { readFile, writeFile } from 'node:fs/promises';
import { gunzipSync } from 'node:zlib';
import path from 'node:path';

function parseArgs(argv) {
	const [input, ...rest] = argv;
	if (!input) {
		console.error('Usage: node restore.mjs <backup.json.gz|backup.json> [--out restore.sql] [--batch 200]');
		process.exit(1);
	}
	let out;
	let batchSize = 200;
	for (let i = 0; i < rest.length; i++) {
		if (rest[i] === '--out') out = rest[++i];
		else if (rest[i] === '--batch') batchSize = Number(rest[++i]);
	}
	if (!out) {
		const base = input.replace(/\.gz$/, '').replace(/\.json$/, '');
		out = `${base}.sql`;
	}
	if (!Number.isFinite(batchSize) || batchSize < 1) batchSize = 200;
	return { input, out, batchSize };
}

/** SQL-literal-encode a JS value pulled out of a D1 `.all()` result. D1/SQLite
 *  values are TEXT | INTEGER | REAL | NULL, or (rarely, not in this schema)
 *  a BLOB serialized as an array of byte values by JSON.stringify. */
function sqlLiteral(value) {
	if (value === null || value === undefined) return 'NULL';
	if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
	if (typeof value === 'boolean') return value ? '1' : '0';
	if (Array.isArray(value)) {
		// Best-effort BLOB support: hex literal.
		const hex = value.map((b) => Number(b).toString(16).padStart(2, '0')).join('');
		return `X'${hex}'`;
	}
	return `'${String(value).replace(/'/g, "''")}'`;
}

function buildInsertStatements(table, rows, batchSize) {
	if (rows.length === 0) return [];
	const columns = Object.keys(rows[0]);
	const statements = [];
	for (let i = 0; i < rows.length; i += batchSize) {
		const batch = rows.slice(i, i + batchSize);
		const valuesSql = batch
			.map((row) => `(${columns.map((col) => sqlLiteral(row[col])).join(', ')})`)
			.join(',\n  ');
		statements.push(
			`INSERT INTO "${table}" (${columns.map((c) => `"${c}"`).join(', ')}) VALUES\n  ${valuesSql};`
		);
	}
	return statements;
}

async function main() {
	const { input, out, batchSize } = parseArgs(process.argv.slice(2));

	const raw = await readFile(input);
	const isGzip = raw.length > 2 && raw[0] === 0x1f && raw[1] === 0x8b;
	const json = isGzip ? gunzipSync(raw).toString('utf-8') : raw.toString('utf-8');
	/** @type {{createdAt: string, schema: string[], tables: Record<string, Record<string, unknown>[]>}} */
	const backup = JSON.parse(json);

	if (!backup.schema || !backup.tables) {
		throw new Error('Not a recognizable Zarparia backup file (missing schema/tables)');
	}

	const lines = [];
	lines.push(`-- Restore generated by restore.mjs from ${path.basename(input)}`);
	lines.push(`-- Original backup createdAt: ${backup.createdAt}`);
	lines.push('');
	lines.push('-- Schema (tables + indexes, in original migration/FK-safe order)');
	lines.push('PRAGMA foreign_keys = OFF; -- disabled while loading; re-enable after if desired');
	for (const stmt of backup.schema) {
		lines.push(stmt.endsWith(';') ? stmt : `${stmt};`);
	}
	lines.push('');

	lines.push('-- Data');
	// Tables are inserted in the same order they appear in backup.schema's
	// CREATE TABLE statements, which preserves FK-safe ordering.
	const tableOrder = backup.schema
		.map((stmt) => /^CREATE TABLE\s+(?:IF NOT EXISTS\s+)?["`]?(\w+)["`]?/i.exec(stmt)?.[1])
		.filter((name) => name && backup.tables[name]);

	let totalRows = 0;
	for (const table of tableOrder) {
		const rows = backup.tables[table] ?? [];
		totalRows += rows.length;
		if (rows.length === 0) {
			lines.push(`-- ${table}: 0 rows`);
			continue;
		}
		lines.push(`-- ${table}: ${rows.length} rows`);
		lines.push(...buildInsertStatements(table, rows, batchSize));
	}
	lines.push('');
	lines.push('PRAGMA foreign_keys = ON;');

	await writeFile(out, lines.join('\n'), 'utf-8');
	console.log(`Wrote ${out} (${tableOrder.length} tables, ${totalRows} rows)`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
