// See https://svelte.dev/docs/kit/types#app.d.ts
/// <reference path="../worker-configuration.d.ts" />

/** A signed-in user, as attached to event.locals by hooks.server.ts. */
export interface SessionUser {
	id: string;
	email: string;
	name: string | null;
	avatarUrl: string | null;
}

declare global {
	namespace App {
		// interface Error {}
		interface Locals {
			user: SessionUser | null;
		}
		// interface PageData {}
		// interface PageState {}
		interface Platform {
			// `Env` is generated by `wrangler types` into worker-configuration.d.ts
			env: Env;
			cf: CfProperties;
			ctx: ExecutionContext;
		}
	}
}

export {};
