// See https://svelte.dev/docs/kit/types#app.d.ts
/// <reference path="../worker-configuration.d.ts" />
import type { SessionUser } from '$lib/types';
import type { Locale } from '$lib/i18n';

declare global {
	namespace App {
		// interface Error {}
		interface Locals {
			user: SessionUser | null;
			locale: Locale;
		}
		// interface PageData {}
		// interface PageState {}
		interface Platform {
			// `Env` is generated by `wrangler types` into worker-configuration.d.ts.
			// Runtime secrets (GOOGLE_CLIENT_ID/SECRET, DEV_AUTH) are read via
			// $lib/server/authenv, which is why they aren't listed here.
			env: Env;
			cf: CfProperties;
			ctx: ExecutionContext;
		}
	}
}

export {};
