// See https://svelte.dev/docs/kit/types#app.d.ts
/// <reference path="../worker-configuration.d.ts" />
import type { SessionUser } from '$lib/types';
import type { Locale } from '$lib/i18n';
import type { ThemeMode } from '$lib/theme';

declare global {
	namespace App {
		// interface Error {}
		interface Locals {
			user: SessionUser | null;
			locale: Locale;
			theme: ThemeMode;
		}
		// interface PageData {}
		interface PageState {
			/** Set by the mobile More sheet (lib/nav/MoreSheet.svelte) via shallow
			 *  routing, purely so the Android/browser Back gesture has an entry to
			 *  consume and closes the sheet instead of leaving the page. Never
			 *  routed on — the URL does not change. */
			moreSheet?: boolean;
			/** Set by the stop guide overlay (lib/trip/GuideSheet.svelte) via
			 *  shallow routing, same purpose as `moreSheet` — gives Back an entry
			 *  to consume so it closes the guide instead of leaving the page. */
			guideSheet?: boolean;
		}
		interface Platform {
			// `Env` is generated by `wrangler types` into worker-configuration.d.ts.
			// Runtime secrets (GOOGLE_CLIENT_ID/SECRET, DEV_AUTH) are read via
			// $lib/server/authenv, which is why they aren't listed here.
			env: Env;
			cf: CfProperties;
			ctx: ExecutionContext;
		}
	}
}

export {};
